plugins {
    id 'java'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/IngsisPrintScript/PrintScript")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
            password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    minHeapSize = "3m" // initial heap size
    maxHeapSize = "6m" // maximum heap size
}

dependencies {
    implementation("PrintScript:com.ingsis.charstream:0.0.0-ci.88.49f95a0")
    implementation("PrintScript:com.ingsis.engine:0.0.0-ci.88.49f95a0")
    implementation("PrintScript:com.ingsis.formatter:0.0.0-ci.88.49f95a0")
    implementation("PrintScript:com.ingsis.interpreter:0.0.0-ci.88.49f95a0")
    implementation("PrintScript:com.ingsis.lexer:0.0.0-ci.88.49f95a0")
    implementation("PrintScript:com.ingsis.parser:0.0.0-ci.88.49f95a0")
    implementation("PrintScript:com.ingsis.sca:0.0.0-ci.88.49f95a0")
    implementation("PrintScript:com.ingsis.utils:0.0.0-ci.88.49f95a0")

    testImplementation 'junit:junit:4.13.1'
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
}
